<header id="homepage">
  <div class="menu-container">
    <a href="<?= BASE_URI; ?>" title="City of Bloomington" class="logo">
      <img
        src="<?= BASE_URI; ?>/<?= THEME; ?>/images/cob-logo-horizontal.svg"
        alt="City of Bloomington, Indiana"
      />
    </a>
    <a href="<?= BASE_URI; ?>" title="City of Bloomington, Indiana" class="name"
      >Mayor John Hamilton</a
    >
  </div>
</header>
