<header id="homepage">
  <div class="menu-container">
    <a href="<?= MAIN_WEBSITE; ?>" title="City of Bloomington" class="logo">
      <img
        src="<?= BASE_URI; ?>/<?= THEME; ?>/images/cob-logo-horizontal.svg"
        alt="City of Bloomington, Indiana"
      />
    </a>
    <a href="<?= MAIN_WEBSITE; ?>" title="City of Bloomington, Indiana" class="name"
      >Mayor John Hamilton</a
    >

    <nav id="navigation" role="navigation" aria-labelledby="navigation">
      <ul>
        <li>
          <a
            href="https://bloomington.in.gov/ureport/miscellaneous/53"
            title="Feedback"
            target="_blank"
            >Feedback</a
          >
        </li>
      </ul>
    </nav>
  </div>
</header>
