---
- hosts: 'search'
  become: 'yes'
  roles:
    - 'City-of-Bloomington.php'

  tasks:
    - name: "Apache site configuration"
      template:
        src: "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/search.conf"
      notify: "apache_restart"

    - name: "Create installation directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
      with_items:
        - "{{ search_install_path }}"
        - "{{ search_site_home    }}"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src:  "{{ search_archive_path }}"
        dest: "{{ search_install_path | dirname }}"
        owner: 'www-data'
        group: 'staff'

    - name: "Update site_config"
      template:
        src: "site_config.j2"
        dest: "{{ search_site_home }}/site_config.php"

    - name: "Update application permissions"
      file:
        path:    "{{ item }}"
        state:   "directory"
        owner:   "www-data"
        group:   "staff"
        mode:    "g+rw"
        recurse: "yes"
      with_items:
        - "{{ search_install_path }}"
        - "{{ search_site_home    }}"
...
